name: buhairi_academy_application
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  smooth_page_indicator: ^2.0.1
  lottie: ^3.3.2
  shared_preferences: ^2.5.4
  curved_navigation_bar: ^1.0.6
  fan_carousel_image_slider: ^1.3.1
  # ملاحظة: تأكد أن هذه المكتبة متوافقة مع إصداراتك
  animated_contact_us: ^0.0.8
  url_launcher: ^6.3.2
  flutter_gen_ai_chat_ui: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/captin_mustafa.png
    - assets/images/teakwondo.png
    - assets/images/teakwondo-boy.png
    - assets/animations/Fist Bump.json
    - assets/images/logo_white.png
    - assets/animations/Scroll down.json
    - assets/images/Screenshot 2025-12-30 150159.png
    - assets/images/Screenshot 2025-12-30 150417.png
    - assets/images/Screenshot 2025-12-30 150449.png
    - assets/images/Screenshot 2025-12-30 150505.png
    - assets/images/Screenshot 2025-12-30 150527.png
    - assets/images/captin_ahmad.png
    - assets/images/captin_bra'.png
    - assets/images/captin_hamza.png
    - assets/images/captin_laila.png
    - assets/images/captin_mohammad.png
    - assets/images/captin_oday.png
    - assets/images/captin_rama.png
    - assets/images/captin_yousef.png
    - assets/animations/Facebook.json
    - assets/animations/Instagram.json
    - assets/animations/whatsapp_loop.json
    - assets/animations/Phone Call.json
    - assets/images/belts.jpeg

  fonts:
    - family: welcomeText
      fonts:
        - asset: assets/fonts/BBHBartle-Regular.ttf
    - family: LoginSignup
      fonts:
        - asset: assets/fonts/MerriweatherSans-Italic-VariableFont_wght.ttf